[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "eth"
publish.workspace = true
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy = { workspace = true, features = ["full"] }

anyhow = { workspace = true }
async-trait = { workspace = true }
ccnext-abi-encoding = { workspace = true }
futures = "0.3.30"
futures-util = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
sp-core = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

# Local dependencies
attestor-primitives = { workspace = true }
mmr = { workspace = true }
pallet-prover-primitives = { workspace = true, features = ["std"] }
utils = { workspace = true }
